apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
      - name: usernode-js
        image: saiteja2502/userprofileretail:latest
        command: ['sh', '-c', 'while true; do echo secret is $SESSION_SECRETVAR and secret is $EMAIL_PASSVAR; sleep 10; done']
        ports:
        - containerPort: 3130  # Change to match your app's port
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/myDatabase"  # Match this to your MongoDB deployment
        - name: SESSION_SECRETVAR
          valueFrom:
            secretkeyRef:
              name: my-secretexample
              key: SESSION_SECRET
        - name: EMAIL_USER
          value: "chagantyteja2502@gmail.com"
        - name: EMAIL_PASSVAR
          valueFrom:
            secretkeyRef:
              name: my-secretexample
              key: EMAIL_PASS
            
        - name: PORT
          value: "3130"
--- 
apiVersion: v1
kind: Service
metadata:
  name: usernode-js-service
spec:
  type: LoadBalancer  # Use NodePort if LoadBalancer is not supported
  ports:
    - port: 3130
      targetPort: 3130
      protocol: TCP
  selector:
    app: userprofile
